// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.19.6
// source: src/timetable/proto/timetable.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "minotor.timetable";

export enum TransferType {
  RECOMMENDED_TRANSFER_POINT = 0,
  TIMED_TRANSFER = 1,
  REQUIRES_MINIMAL_TIME = 2,
  IN_SEAT_TRANSFER = 3,
  UNRECOGNIZED = -1,
}

export function transferTypeFromJSON(object: any): TransferType {
  switch (object) {
    case 0:
    case "RECOMMENDED_TRANSFER_POINT":
      return TransferType.RECOMMENDED_TRANSFER_POINT;
    case 1:
    case "TIMED_TRANSFER":
      return TransferType.TIMED_TRANSFER;
    case 2:
    case "REQUIRES_MINIMAL_TIME":
      return TransferType.REQUIRES_MINIMAL_TIME;
    case 3:
    case "IN_SEAT_TRANSFER":
      return TransferType.IN_SEAT_TRANSFER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransferType.UNRECOGNIZED;
  }
}

export function transferTypeToJSON(object: TransferType): string {
  switch (object) {
    case TransferType.RECOMMENDED_TRANSFER_POINT:
      return "RECOMMENDED_TRANSFER_POINT";
    case TransferType.TIMED_TRANSFER:
      return "TIMED_TRANSFER";
    case TransferType.REQUIRES_MINIMAL_TIME:
      return "REQUIRES_MINIMAL_TIME";
    case TransferType.IN_SEAT_TRANSFER:
      return "IN_SEAT_TRANSFER";
    case TransferType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RouteType {
  TRAM = 0,
  SUBWAY = 1,
  RAIL = 2,
  BUS = 3,
  FERRY = 4,
  CABLE_TRAM = 5,
  AERIAL_LIFT = 6,
  FUNICULAR = 7,
  TROLLEYBUS = 8,
  MONORAIL = 9,
  UNRECOGNIZED = -1,
}

export function routeTypeFromJSON(object: any): RouteType {
  switch (object) {
    case 0:
    case "TRAM":
      return RouteType.TRAM;
    case 1:
    case "SUBWAY":
      return RouteType.SUBWAY;
    case 2:
    case "RAIL":
      return RouteType.RAIL;
    case 3:
    case "BUS":
      return RouteType.BUS;
    case 4:
    case "FERRY":
      return RouteType.FERRY;
    case 5:
    case "CABLE_TRAM":
      return RouteType.CABLE_TRAM;
    case 6:
    case "AERIAL_LIFT":
      return RouteType.AERIAL_LIFT;
    case 7:
    case "FUNICULAR":
      return RouteType.FUNICULAR;
    case 8:
    case "TROLLEYBUS":
      return RouteType.TROLLEYBUS;
    case 9:
    case "MONORAIL":
      return RouteType.MONORAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RouteType.UNRECOGNIZED;
  }
}

export function routeTypeToJSON(object: RouteType): string {
  switch (object) {
    case RouteType.TRAM:
      return "TRAM";
    case RouteType.SUBWAY:
      return "SUBWAY";
    case RouteType.RAIL:
      return "RAIL";
    case RouteType.BUS:
      return "BUS";
    case RouteType.FERRY:
      return "FERRY";
    case RouteType.CABLE_TRAM:
      return "CABLE_TRAM";
    case RouteType.AERIAL_LIFT:
      return "AERIAL_LIFT";
    case RouteType.FUNICULAR:
      return "FUNICULAR";
    case RouteType.TROLLEYBUS:
      return "TROLLEYBUS";
    case RouteType.MONORAIL:
      return "MONORAIL";
    case RouteType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Route {
  /**
   * Arrivals and departures encoded as a 16 bit uint array.
   * Format: [arrival1, departure1, arrival2, departure2, etc.]
   */
  stopTimes: Uint8Array;
  /**
   * PickUp and DropOff types represented as an 8 bit uint array.
   * Values:
   *   0: REGULAR
   *   1: NOT_AVAILABLE
   *   2: MUST_PHONE_AGENCY
   *   3: MUST_COORDINATE_WITH_DRIVER
   * Format: [drop_off_1][pickup_1][drop_off_0][pickup_0]
   * 2 bits per value
   */
  pickUpDropOffTypes: Uint8Array;
  /**
   * Stops encoded as a 32 bit uint array.
   * Format: [stop1, stop2, stop3, etc.]
   */
  stops: Uint8Array;
  serviceRouteId: number;
}

export interface Transfer {
  destination: number;
  type: TransferType;
  minTransferTime?: number | undefined;
}

export interface StopAdjacency {
  transfers: Transfer[];
  routes: number[];
}

export interface ServiceRoute {
  type: RouteType;
  name: string;
  routes: number[];
}

export interface Timetable {
  version: string;
  stopsAdjacency: StopAdjacency[];
  routesAdjacency: Route[];
  serviceRoutes: ServiceRoute[];
}

function createBaseRoute(): Route {
  return {
    stopTimes: new Uint8Array(0),
    pickUpDropOffTypes: new Uint8Array(0),
    stops: new Uint8Array(0),
    serviceRouteId: 0,
  };
}

export const Route: MessageFns<Route> = {
  encode(message: Route, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stopTimes.length !== 0) {
      writer.uint32(10).bytes(message.stopTimes);
    }
    if (message.pickUpDropOffTypes.length !== 0) {
      writer.uint32(18).bytes(message.pickUpDropOffTypes);
    }
    if (message.stops.length !== 0) {
      writer.uint32(26).bytes(message.stops);
    }
    if (message.serviceRouteId !== 0) {
      writer.uint32(32).uint32(message.serviceRouteId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Route {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stopTimes = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pickUpDropOffTypes = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stops = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serviceRouteId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Route {
    return {
      stopTimes: isSet(object.stopTimes) ? bytesFromBase64(object.stopTimes) : new Uint8Array(0),
      pickUpDropOffTypes: isSet(object.pickUpDropOffTypes)
        ? bytesFromBase64(object.pickUpDropOffTypes)
        : new Uint8Array(0),
      stops: isSet(object.stops) ? bytesFromBase64(object.stops) : new Uint8Array(0),
      serviceRouteId: isSet(object.serviceRouteId) ? globalThis.Number(object.serviceRouteId) : 0,
    };
  },

  toJSON(message: Route): unknown {
    const obj: any = {};
    if (message.stopTimes.length !== 0) {
      obj.stopTimes = base64FromBytes(message.stopTimes);
    }
    if (message.pickUpDropOffTypes.length !== 0) {
      obj.pickUpDropOffTypes = base64FromBytes(message.pickUpDropOffTypes);
    }
    if (message.stops.length !== 0) {
      obj.stops = base64FromBytes(message.stops);
    }
    if (message.serviceRouteId !== 0) {
      obj.serviceRouteId = Math.round(message.serviceRouteId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Route>, I>>(base?: I): Route {
    return Route.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Route>, I>>(object: I): Route {
    const message = createBaseRoute();
    message.stopTimes = object.stopTimes ?? new Uint8Array(0);
    message.pickUpDropOffTypes = object.pickUpDropOffTypes ?? new Uint8Array(0);
    message.stops = object.stops ?? new Uint8Array(0);
    message.serviceRouteId = object.serviceRouteId ?? 0;
    return message;
  },
};

function createBaseTransfer(): Transfer {
  return { destination: 0, type: 0, minTransferTime: undefined };
}

export const Transfer: MessageFns<Transfer> = {
  encode(message: Transfer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.destination !== 0) {
      writer.uint32(8).uint32(message.destination);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.minTransferTime !== undefined) {
      writer.uint32(24).uint32(message.minTransferTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transfer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransfer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.destination = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minTransferTime = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transfer {
    return {
      destination: isSet(object.destination) ? globalThis.Number(object.destination) : 0,
      type: isSet(object.type) ? transferTypeFromJSON(object.type) : 0,
      minTransferTime: isSet(object.minTransferTime) ? globalThis.Number(object.minTransferTime) : undefined,
    };
  },

  toJSON(message: Transfer): unknown {
    const obj: any = {};
    if (message.destination !== 0) {
      obj.destination = Math.round(message.destination);
    }
    if (message.type !== 0) {
      obj.type = transferTypeToJSON(message.type);
    }
    if (message.minTransferTime !== undefined) {
      obj.minTransferTime = Math.round(message.minTransferTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transfer>, I>>(base?: I): Transfer {
    return Transfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transfer>, I>>(object: I): Transfer {
    const message = createBaseTransfer();
    message.destination = object.destination ?? 0;
    message.type = object.type ?? 0;
    message.minTransferTime = object.minTransferTime ?? undefined;
    return message;
  },
};

function createBaseStopAdjacency(): StopAdjacency {
  return { transfers: [], routes: [] };
}

export const StopAdjacency: MessageFns<StopAdjacency> = {
  encode(message: StopAdjacency, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transfers) {
      Transfer.encode(v!, writer.uint32(10).fork()).join();
    }
    writer.uint32(18).fork();
    for (const v of message.routes) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopAdjacency {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopAdjacency();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transfers.push(Transfer.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.routes.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.routes.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StopAdjacency {
    return {
      transfers: globalThis.Array.isArray(object?.transfers)
        ? object.transfers.map((e: any) => Transfer.fromJSON(e))
        : [],
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: StopAdjacency): unknown {
    const obj: any = {};
    if (message.transfers?.length) {
      obj.transfers = message.transfers.map((e) => Transfer.toJSON(e));
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StopAdjacency>, I>>(base?: I): StopAdjacency {
    return StopAdjacency.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopAdjacency>, I>>(object: I): StopAdjacency {
    const message = createBaseStopAdjacency();
    message.transfers = object.transfers?.map((e) => Transfer.fromPartial(e)) || [];
    message.routes = object.routes?.map((e) => e) || [];
    return message;
  },
};

function createBaseServiceRoute(): ServiceRoute {
  return { type: 0, name: "", routes: [] };
}

export const ServiceRoute: MessageFns<ServiceRoute> = {
  encode(message: ServiceRoute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    writer.uint32(26).fork();
    for (const v of message.routes) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceRoute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.routes.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.routes.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceRoute {
    return {
      type: isSet(object.type) ? routeTypeFromJSON(object.type) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: ServiceRoute): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = routeTypeToJSON(message.type);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceRoute>, I>>(base?: I): ServiceRoute {
    return ServiceRoute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceRoute>, I>>(object: I): ServiceRoute {
    const message = createBaseServiceRoute();
    message.type = object.type ?? 0;
    message.name = object.name ?? "";
    message.routes = object.routes?.map((e) => e) || [];
    return message;
  },
};

function createBaseTimetable(): Timetable {
  return { version: "", stopsAdjacency: [], routesAdjacency: [], serviceRoutes: [] };
}

export const Timetable: MessageFns<Timetable> = {
  encode(message: Timetable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== "") {
      writer.uint32(10).string(message.version);
    }
    for (const v of message.stopsAdjacency) {
      StopAdjacency.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.routesAdjacency) {
      Route.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.serviceRoutes) {
      ServiceRoute.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Timetable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimetable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stopsAdjacency.push(StopAdjacency.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.routesAdjacency.push(Route.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serviceRoutes.push(ServiceRoute.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Timetable {
    return {
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      stopsAdjacency: globalThis.Array.isArray(object?.stopsAdjacency)
        ? object.stopsAdjacency.map((e: any) => StopAdjacency.fromJSON(e))
        : [],
      routesAdjacency: globalThis.Array.isArray(object?.routesAdjacency)
        ? object.routesAdjacency.map((e: any) => Route.fromJSON(e))
        : [],
      serviceRoutes: globalThis.Array.isArray(object?.serviceRoutes)
        ? object.serviceRoutes.map((e: any) => ServiceRoute.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Timetable): unknown {
    const obj: any = {};
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.stopsAdjacency?.length) {
      obj.stopsAdjacency = message.stopsAdjacency.map((e) => StopAdjacency.toJSON(e));
    }
    if (message.routesAdjacency?.length) {
      obj.routesAdjacency = message.routesAdjacency.map((e) => Route.toJSON(e));
    }
    if (message.serviceRoutes?.length) {
      obj.serviceRoutes = message.serviceRoutes.map((e) => ServiceRoute.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Timetable>, I>>(base?: I): Timetable {
    return Timetable.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Timetable>, I>>(object: I): Timetable {
    const message = createBaseTimetable();
    message.version = object.version ?? "";
    message.stopsAdjacency = object.stopsAdjacency?.map((e) => StopAdjacency.fromPartial(e)) || [];
    message.routesAdjacency = object.routesAdjacency?.map((e) => Route.fromPartial(e)) || [];
    message.serviceRoutes = object.serviceRoutes?.map((e) => ServiceRoute.fromPartial(e)) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
